### ISSUE TITLE
Add avatar images to workshops

### ISSUE THREAD

**Issue by mbullington** [Hack-PSU/frontend-app#22]
What's kinda annoying is, for the workshops, images are baked into the frontend repo and aren't part of the API:
https://github.com/Hack-PSU/frontend/blob/bcc2953f319f543449d705eede74a1f3a0e269f1/user-registration-app/src/app/views/live-view/live-view.component.html

I don't know how we could do this easily without doubling the work, is there any way these could be hosted on backend API / admin app instead? @jmm8046

**Comment by jmm8046** [comment]
I'm assuming you're talking about the presenter images? Do you think we need them on the app or could we just have a standard image, maybe its different between workshop levels. 

I'm not sure what you're planning on the layout for the workshop cards though. If you think the UI would look a lot better with the presenter images, I'm sure @stan29308 can cook something up server side and so we can store it in the db (maybe instead of through the adminapp we can just send a POST request? at least for a mvp)

**Comment by rsquared226** [comment]
@jmm8046 Well this is what it looks like (with fake data). If it's too much work I think we can keep it this way for now and work on it later if we have extra time.

![Screenshot_20200218-150754](https://user-images.githubusercontent.com/7365763/74774463-c8a84e00-5261-11ea-8646-b58a5d30a715.jpg)

**Comment by mbullington** [comment]
Good call! I think circling around if we have time is the best approach, even though I'd like profile pictures.
